In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[1:5] = 100

In [7]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)

In [9]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [10]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])